### ISSUE TITLE
Project to github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mblanchette/maven-java-formatter-plugin#36]
```
Can this project get migrated to github?  It would make contributions much 
easier.
```

Original issue reported on code.google.com by `hazen...@gmail.com` on 18 Sep 2014 at 3:01

**Comment by hazendaz** [comment]
I'm going to have a pretty large pull request for this effort.  I had done this long enough ago that I had made all sorts of enhancements sense.  If you want this broken into separate pull requests just let me know.  I have rebased against your new master here in github and fixed any merge conflicts.  I also normalized the codebase which landing in one of the many commits I had.  There were a number of commits I dropped as things came over on your end with various duplicates of what I also did.  So I went with your cuts.  The pull request will be coming very shortly.

**Comment by mblanchette** [comment]
See merge in #37
